[build]
builder = "nixpacks"

[deploy]
startCommand = "python minimal_backend.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/"
timeout = 300
interval = 30 